name: Build

on:
  push:
    branches: [ master ]

jobs:
  unittests-n-commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6.12, 3.7, 3.8, 3.9 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dataclasses
        pipenv install pbr
    - name: Test with unittest
      run: |
        python -m unittest discover -s tests/
        python -m unittest discover -s tests_standalone
        python -m unittest discover -s tests_standalone_2
